name:                og-scrape
version:             0.1.0.0
github:              "emiflake/og-scrape"
license:             BSD3
author:              "Emily Martins"
maintainer:          "emily.flakeheart@gmail.com"
copyright:           "2019 Emily Martins"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         An Open Graph Protocol Scraper

dependencies:
- base          >= 4.7 && < 5
- tagsoup       == 0.14.8
- scotty        == 0.11.5
- aeson         == 1.4.4.0
- http-conduit  == 2.3.7.3
- bytestring    == 0.10.10.0
- text          == 1.2.4.0
- pretty-simple == 3.1.0.0
- containers    == 0.6.0.1

library:
  source-dirs: src

executables:
  og-scrape-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - og-scrape

tests:
  og-scrape-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - og-scrape
